services:
  mongodb:
    image: mongo:latest
    container_name: blog_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app_network

  postgres:
    image: postgres:13
    container_name: blog_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: blog_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  django_backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./api/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/blog_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=$POSTGRES_HOST
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=1
    networks:
      - app_network

  express_backend:
    build:
      context: ./api-express
      dockerfile: Dockerfile
    container_name: express_backend
    ports:
      - "5000:5000"
    volumes:
      - ./api-express:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - ./api-express/.env
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/blog_api?authSource=admin
      - PORT=5000
    networks:
      - app_network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: blog_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - VITE_EXPRESS_API_URL=http://localhost:5000
      - VITE_DJANGO_API_URL=http://localhost:8000
    depends_on:
      - express_backend
      - django_backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
  redis_data:
  django_static:
  django_media:
  express_uploads:
  frontend_dist: